#!/bin/bash

# run as ./strip-trace 0 100 downlink_prefix uplink_prefix
# not sure if works if the first number is not 0 :)
# I don't understand how these timestamp work

tstart=$1
tend=$2
uplink=$3
downlink=$4
first=-1

echo "from $tstart to $tend"

while read number
do
  if [ "$number" -ge "$tstart" ] ; then
    if [ $first -le -1 ] ; then
      first=$number
    fi
    if [ "$number" -le "$tend" ] ; then
      echo $((number-first))
    else
      break
    fi
  fi
done < $downlink.ms > $downlink-$tstart-$tend.ms

first=-1
while read number
do
  if [ "$number" -ge "$tstart" ] ; then
    if [ $first -le -1 ] ; then
      first=$number
    fi
    if [ "$number" -le "$tend" ] ; then
      echo $((number-first))
    else
      break
    fi
  fi
done < $uplink.ms > $uplink-$tstart-$tend.ms

