#!/bin/bash

# run as ./strip-trace 0 100
# not sure if works if the first number is not 0 :)
# I don't understand how these timestamp work

tstart=$1
tend=$2
first=-1

echo "from $tstart to $tend"

while read number
do
  if [ "$number" -ge "$tstart" ] ; then
    if [ $first -le -1 ] ; then
      first=$number
    fi
    if [ "$number" -le "$tend" ] ; then
      echo $((number-first))
    else
      break
    fi
  fi
done < ../att_downlink.ms > ../att_downlink-$tstart-$tend.ms

first=-1
while read number
do
  if [ "$number" -ge "$tstart" ] ; then
    if [ $first -le -1 ] ; then
      first=$number
    fi
    if [ "$number" -le "$tend" ] ; then
      echo $((number-first))
    else
      break
    fi
  fi
done < ../att_uplink.ms > ../att_uplink-$tstart-$tend.ms

